name: Spellcheck Markdown
on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.md'

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: matheus23/md-spellcheck-action@v4.2.2
        with:
          files-to-check: "**.md"
          words-to-ignore-file: "config/spellcheck-ignore.txt"