name: PR JSON Check

on:
  pull_request:
    branches: [ main ] 

jobs:
  test-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Find and check creator_mail
        run: |
            base_sha=${{ github.event.pull_request.base.sha }}
            head_sha=${{ github.event.pull_request.head.sha }}

            echo "Comparing base commit $base_sha with head commit $head_sha"

            # Get a list of changed JSON files. The `|| true` ensures this line
            # doesn't fail the script if no .json files are found.
            json_files=$(git diff --name-only $base_sha $head_sha | grep '.json$' || true)

            # Check if the result is empty. If so, it's a success.
            if [ -z "$json_files" ]; then
                echo "No JSON files were changed in this PR. ✅"
                exit 0 # Explicitly exit with a success code
            fi

      - name: Check for email address in JSON files
        run: |
            # If we get here, files were found. Now loop and check them.
            echo "Checking the following JSON files:"
            echo "$json_files"

            for file in $json_files; do
                echo "---"
                echo "Checking file: $file"
                if ! grep -q '"creator_mail":' "$file"; then
                echo "➡️ Key 'creator_mail' not found in $file. Skipping."
                continue
                fi

                creator_mail_value=$(jq -r '.creator_mail' "$file")
                if [ "$creator_mail_value" == "" ]; then
                echo "✅ Success: 'creator_mail' is an empty string."
                else
                echo "❌ Error: 'creator_mail' should be an empty string, but found '$creator_mail_value'."
                exit 1
                fi
            done

            echo "---"
            echo "All checks passed for all JSON files. 🎉"